export const datamuse = [
    { id: 1, name: "Synonyms", keyword: "rel_syn" },
    { id: 2, name: "Antonyms", keyword: "rel_ant" },
    { id: 3, name: "Kind of", keyword: "rel_spc" },
    { id: 4, name: "Hyponyms", keyword: "rel_gen" },
    { id: 5, name: "Holonyms", keyword: "rel_com" },
    { id: 6, name: "Means like", keyword: "ml" },
    { id: 7, name: "Sounds like", keyword: "sl" },
    { id: 8, name: "Spelled like", keyword: "sp" },
    { id: 9, name: "Nouns", keyword: "rel_jja" },
    { id: 10, name: "Adjectives", keyword: "rel_jjb" },
    { id: 11, name: "Triggers", keyword: "rel_trg" },
    { id: 12, name: "Meronyms", keyword: "rel_par" },
    { id: 13, name: "Followers", keyword: "rel_bga" },
    { id: 14, name: "Predecessors", keyword: "rel_bgb" },
    { id: 15, name: "Perfect Rhymes", keyword: "rel_rhy" },
    { id: 16, name: "Aprox Rhymes", keyword: "rel_nry" },
    { id: 17, name: "Homophones", keyword: "rel_hom" },
    { id: 18, name: "Consonant Match", keyword: "rel_cns" },
];
